apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: neocar-rent-hpa
  namespace: neocar-rent
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: neocar-rent
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60  # Déclenche le scale-up si l'utilisation CPU > 60%
