apiVersion: v1
kind: Service
metadata:
  name: neocar-rent-service
  namespace: neocar-rent
spec:
  type: NodePort
  selector:
    app: neocar-rent
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 33443 # Tu peux choisir un port entre 30000 et 32767
